# Build the obfs4 binary (cross-compiling)
FROM --platform=$BUILDPLATFORM golang:1.27-alpine@sha256:4c9fe60190a2a3350ddc51de80d0224b8a6698d12bdfc999fee45ea9d6c46dbc AS obfs-builder
ARG LYREBIRD_VERSION="lyrebird-0.8.1"

RUN apk add --update --no-cache git && \
      git clone https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird.git --depth 1 --branch "${LYREBIRD_VERSION}" /lyrebird

# Build lyrebird
WORKDIR /lyrebird
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags="-X main.lyrebirdVersion=$(VERSION)" ./cmd/lyrebird

# Tor runner
FROM docker.io/library/alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b AS runner

LABEL org.opencontainers.image.source="https://github.com/rinsecode/tor-docker"

WORKDIR /app
ENV HOME=/app

ARG TOR_VERSION=0.4.9.8
RUN apk add --update --no-cache \
      tor=~"${TOR_VERSION}" && \
    chmod -R g+w /app /run

# fix hard coded path for controller
RUN ln -s /usr/bin/tor /usr/local/bin/tor

# install transports
COPY --from=lyrebird-builder /lyrebird/lyrebird /usr/local/bin/.

# create service dir (we don't define VOLUME because https://github.com/docker-library/mysql/issues/255
# and other issues when running as non-root user)
RUN mkdir -p /run/tor/service && chown -R 1001 /run/tor

# change to non root
USER 1001

ENTRYPOINT ["/usr/local/bin/tor"]
