# Build the obfs4 binary (cross-compiling)
FROM --platform=$BUILDPLATFORM golang:1.26.4-alpine@sha256:f23e8b227fb4493eabe03bede4d5a32d04092da71962f1fb79b5f7d1e6c2a17f AS obfs-builder
ARG LYREBIRD_VERSION="lyrebird-0.8.1"

RUN apk add --update --no-cache git && \
      git clone https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird.git --depth 1 --branch "${LYREBIRD_VERSION}" /lyrebird

# Build lyrebird
WORKDIR /lyrebird
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags="-X main.lyrebirdVersion=$(VERSION)" ./cmd/lyrebird

# Tor runner
FROM docker.io/library/alpine:3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4 AS runner

LABEL org.opencontainers.image.source="https://github.com/rinsecode/tor-docker"

WORKDIR /app
ENV HOME=/app

ARG TOR_VERSION=0.4.9.8
RUN apk add --update --no-cache \
      tor=~"${TOR_VERSION}" && \
    chmod -R g+w /app /run

# fix hard coded path for controller
RUN ln -s /usr/bin/tor /usr/local/bin/tor

# install transports
COPY --from=lyrebird-builder /lyrebird/lyrebird /usr/local/bin/.

# create service dir (we don't define VOLUME because https://github.com/docker-library/mysql/issues/255
# and other issues when running as non-root user)
RUN mkdir -p /run/tor/service && chown -R 1001 /run/tor

# change to non root
USER 1001

ENTRYPOINT ["/usr/local/bin/tor"]
